name: futsals
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  awesome_icons: ^1.1.0
  carousel_slider: ^4.2.1
  flutter_image_slider: ^0.0.2
  calendar_view: ^1.0.2
  table_calendar: ^3.0.9
  font_awesome_flutter: ^10.4.0

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
 
